#ifndef __PERF_H__
#define __PERF_H__

#include <stdint.h>

// Event IDs
enum {
    EVENT_IFU_FETCH = 0,
    EVENT_IFU_STALL_ICACHE,
    EVENT_IFU_STALL_IDU,
    EVENT_LSU_READ,
    EVENT_LSU_WRITE,
    EVENT_LSU_LATENCY,
    EVENT_EXU_COMP,
    EVENT_INST_TYPE_COMPUTE,
    EVENT_INST_TYPE_LOAD,
    EVENT_INST_TYPE_STORE,
    EVENT_INST_TYPE_CSR,
    EVENT_INST_TYPE_BRANCH,
    EVENT_INST_TYPE_JUMP,
    EVENT_INST_TYPE_OTHER,
    EVENT_ICACHE_MISS,
    EVENT_BPU_PREDICT,
    EVENT_BPU_MISPRED,
    EVENT_MUL,
    EVENT_DIV,
    EVENT_COMMIT,
    EVENT_ROB_FULL,
    EVENT_FL_EMPTY,
    EVENT_RS_FULL,
    EVENT_FQ_FULL,
    EVENT_FQ_EMPTY,
    EVENT_BP_FLUSH,
    EVENT_CDB_CONFLICT,
    EVENT_CDB_BLOCKED,
    EVENT_COMMIT_HEAD_WAIT,
    EVENT_COMMIT_WAIT_STORE,
    EVENT_COMMIT_WAIT_FENCE,
    EVENT_COMMIT_WAIT_BP,
    EVENT_COMMIT_WAIT_FLUSH,
    EVENT_LSU_SQ_WAIT,
    EVENT_LSU_SQ_FORWARD,
    EVENT_LSU_BUS_WAIT,
    EVENT_BPU_DIR_MISPRED,
    EVENT_BPU_TARGET_MISPRED,
    EVENT_BPU_UNPREDICTED,
    EVENT_STORE_BUFFER_ENQ,
    EVENT_STORE_BUFFER_DRAIN,
    EVENT_STORE_BUFFER_FULL,
    EVENT_STORE_BUFFER_FORWARD,
    EVENT_DCACHE_ACCESS,
    EVENT_DCACHE_HIT,
    EVENT_DCACHE_MISS,
    EVENT_DCACHE_BYPASS,
    EVENT_FETCH_SLOT0_VALID,
    EVENT_FETCH_SLOT1_VALID,
    EVENT_FETCH_SLOT1_KILLED,
    EVENT_FQ_ENQ2,
    EVENT_FQ_SPACE_ONE,
    EVENT_FETCH_REDIRECT_BUBBLE,
    EVENT_BPU_TAGGED_HIT,
    EVENT_BPU_INDIRECT_HIT,
    EVENT_COMMIT_SLOT0,
    EVENT_COMMIT_SLOT1,
    EVENT_COMMIT2,
    EVENT_COMMIT_SLOT1_BLOCK,
    EVENT_COMMIT_SLOT1_NOT_READY,
    EVENT_COMMIT_SLOT1_BLOCK_SLOT0_EXCL,
    EVENT_COMMIT_SLOT1_BLOCK_MEM,
    EVENT_COMMIT_SLOT1_BLOCK_CTRL,
    EVENT_COMMIT_SLOT1_BLOCK_CSR,
    EVENT_COMMIT_SLOT1_BLOCK_SPECIAL,
    EVENT_COMMIT_SLOT1_BLOCK_BP,
    EVENT_MAX
};

#ifdef __cplusplus
extern "C" {
#endif

void npc_pm_event(int event_id, long long data);
void print_perf_stats(unsigned long long cycles);

#ifdef __cplusplus
}
#endif

#endif
