CSRC_LIB = $(filter-out %/sim_cpu.cpp %/sim_main.cpp %/trace_diff.cpp %/difftest.cpp %/ref.cpp, $(CSRC))
CSRC_LIB += $(CHISEL_WORK_DIR)/../pipeline_chisel_soc_csrc/difftest/ref_so.cpp

NPC_SO = $(BUILD_DIR)/npc-ref.so
SO_OBJ_DIR = $(BUILD_DIR)/so_obj_dir

$(NPC_SO): $(VSRC) $(CSRC_LIB)
	@echo "Building NPC Shared Object: $@"
	mkdir -p $(dir $@)
	rm -rf $(SO_OBJ_DIR)
	$(VERILATOR) $(VERILATOR_FLAGS) +define+NO_UART_PRINT \
		--top-module $(TOP_MODULE) \
		--Mdir $(SO_OBJ_DIR) \
		--cc --exe --build \
		$(abspath $(CSRC_LIB)) $(VSRC) \
		-CFLAGS "-fPIC -D_NPC_SO_BUILD" \
		-LDFLAGS "-shared" \
		-I$(NPC_HOME)/../ysyxSoC/perip/uart16550/rtl \
		-I$(NPC_HOME)/../ysyxSoC/perip/spi/rtl \
		-o $(abspath $@)

lib: $(NPC_SO)